### ISSUE TITLE
Error: no context directory and no Containerfile specified

### ISSUE THREAD

**Issue by mayank-kabra2001** [benycze/bsc-docker-container#2]
in which directory do we need to go and use this command :  

![Screenshot from 2020-10-07 20-05-05](https://user-images.githubusercontent.com/57330493/95345595-860eb100-08d8-11eb-834c-78ee4054ae2e.png)

podman build -t localhost/bsc-compiler --build-arg BJOBS=4 .

I have used it in both directories but they are saying their is no directory .

**Comment by benycze** [comment]
Hi @mayank-kabra2001,

it seems you have entered the command incorrectly. The `.` at the end of the command is important because it specifies the context (e.g., where the tool finds the Dockerfile).

Run the command as is in the README in the repository root (for podman):

```bash
git clone https://github.com/benycze/bsc-docker-container.git
cd bsc-docker-container
bash bootstrap.sh
podman build -t localhost/bsc-compiler --build-arg BJOBS=4 .
```

Best,
Beny

**Comment by mayank-kabra2001** [comment]
![Screenshot from 2020-10-10 22-16-07](https://user-images.githubusercontent.com/57330493/95660574-7d231700-0b46-11eb-9df9-54663bfda0f1.png)
please help me out with this i got stuck here .
