### ISSUE TITLE
recipe for target 'bsc' failed

### ISSUE THREAD

**Issue by mayank-kabra2001** [benycze/bsc-docker-container#3]
![Screenshot from 2020-10-10 22-16-07](https://user-images.githubusercontent.com/57330493/95660618-a93e9800-0b46-11eb-8162-86150b823649.png)
please help me out with this , im stuck here .

**Comment by benycze** [comment]
It seems you are out of memory during the compilation. Try to translate with one job:

```bash
podman build -t localhost/bsc-compiler --build-arg BJOBS=1 .
```

**Comment by mayank-kabra2001** [comment]
it is done but not able to find that directory 
![Screenshot from 2020-10-12 12-56-38](https://user-images.githubusercontent.com/57330493/95717410-8917f180-0c8a-11eb-86ec-ce26999c4d87.png)

**Comment by benycze** [comment]
Hi @mayank-kabra2001,

the error reported by podman means that it cannot find the source folder. You need to correct the path of mounted folder (I am supposing your `bsc-work` folder already exists. Also, fix the command if it will not work because I am writing it from hearth):

```bash
docker run --rm -t -i --mount=type=bind,source=/home/atom/bsc-work,destination=/bsc-work localhost/bsc-compiler bash
```

Beny

**Comment by mayank-kabra2001** [comment]
Hi @benycze 

Thanks a lot for your guidance . Its working now correctly .
